volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      - "com.centurylinklabs.watchtower.schedule=0 0 2 1 * *"  # Monthly update on 1st day at 2 AM

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "com.centurylinklabs.watchtower.schedule=0 0 2 * * 1"  # Weekly update on Monday at 2 AM

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=0 0 1 * * *  # Check for updates daily at 1 AM
      - WATCHTOWER_CLEANUP=true  # Remove old images after update
      - WATCHTOWER_INCLUDE_STOPPED=true  # Also update stopped containers
      - WATCHTOWER_INCLUDE_RESTARTING=true  # Also update restarting containers
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Don't update watchtower itself

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --config /home/nonroot/.cloudflared/config.yml run
    volumes:
      - ~/.cloudflared:/home/nonroot/.cloudflared:ro
    depends_on:
      - n8n
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - tunnel
